services:
  test:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 3000
    restart: always
    command: ./entry.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plainhtml.rule=Host(`plainhtml.iamon99.com`)"
      - "traefik.http.routers.plainhtml.entrypoints=websecure"
      - "traefik.http.routers.plainhtml.tls.certresolver=myresolver"
      - "traefik.http.services.plainhtml.loadbalancer.server.port=3000"
