# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  next:
    build: .
    ports:
      - 3000
    restart: always
    working_dir: /app
    volumes:
      - $PWD:/app
      - next12_node_modules:/app/node_modules
    command: sleep infinity
    # command: ./entry_point.sh
    user: 1000:1000

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.docker-next12-seo-http.rule=Host(`docker-next12-seo.iamon99.com`)'
      - 'traefik.http.routers.docker-next12-seo-http.entrypoints=web'
      - 'traefik.http.routers.docker-next12-seo-http.middlewares=docker-next12-seo-https'
      - 'traefik.http.middlewares.docker-next12-seo-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.docker-next12-seo.rule=Host(`docker-next12-seo.iamon99.com`)'
      - 'traefik.http.routers.docker-next12-seo.entrypoints=websecure'
      - 'traefik.http.routers.docker-next12-seo.tls.certresolver=myresolver'
      - 'traefik.http.services.docker-next12-seo.loadbalancer.server.port=3000'

networks:
  default:
    external:
      name: traefik-proxy-network

volumes:
  next12_node_modules:
